clear;close all;
M=32;
fp=1000;fs=2000;Fs=8000;
Ap=2;As=6;
wp=2*fp/Fs;
ws=2*fs/Fs;
[N,wn]=buttord(wp,ws,Ap,As);
[b,a]=butter(N,wn);
[bz,az]=bilinear(b,a,Fs);
[H,f]=freqz(b,a,2048,Fs);
f1=500;f2=2000;
Fs2=8000;
t=0:(1/Fs2):(6/min([f2,f1]));
x=sin(2*pi*f1*t)+sin(2*pi*f2*t);
n=length(x);
X=abs(fft(x,n));
fas=Fs2*(0:N-1)/N;
y=filter(b,a,x);
ny=length(y);
Y=abs(fft(y,ny));
ab=20*log10(abs(H/abs(max(H))));
a=angle(H);


subplot(411);
plot(fas,X/max(X),'r');
set(gca,'xlim',[0 Fs2/2],'ylim',[0 1 ]);
xlabel('frequency');
ylabel('Magnitude');
title('Spectrum of Input Signal');
subplot(412);
plot(f,ab,'b');
xlabel('frequency');
ylabel('Magnitude');
title('Magnitude Response of LPF (Butterworth)');
subplot(413);
plot(f,a,'g');
xlabel('frequency');
ylabel('Phase');
title('Phase Response of LPF (Butterworth)');
subplot(414);
plot(fas,Y/max(Y),'m');
set(gca,'xlim',[0 Fs2/2],'ylim',[0 1]);
xlabel('frequency');